// Temas que a Mary pode escolher. Cada tema redefine as cores e degradês
// principais do app. Funciona em iOS, Android e web (multiplataforma).

export const THEMES = {
  rose: {
    id: 'rose',
    label: 'Rosa',
    emoji: '🌹',
    desc: 'O clássico romântico',
    home: ['#FFF0F5', '#FFD6E8', '#FFAEC9', '#FF85A1'],
    counter: ['#C0395A', '#E8527A', '#FF85A1'],
    accent: '#C0395A',
    accentLight: '#E8527A',
    accentDark: '#8B1E3F',
    textDark: '#3D1021',
    textMedium: '#8B4560',
    textLight: '#C48EA0',
    cardBg: '#FFFFFF',
    chipBg: '#FFF0F5',
    statusBar: 'dark',
  },
  sakura: {
    id: 'sakura',
    label: 'Sakura',
    emoji: '🌸',
    desc: 'Flor de cerejeira suave',
    home: ['#FFF5F8', '#FFE3EF', '#FFC6DD', '#FFA6C9'],
    counter: ['#E06B9A', '#F48FB1', '#FFC1D9'],
    accent: '#D6517E',
    accentLight: '#F48FB1',
    accentDark: '#A83D63',
    textDark: '#43152B',
    textMedium: '#94556F',
    textLight: '#C99CB0',
    cardBg: '#FFFFFF',
    chipBg: '#FFF0F6',
    statusBar: 'dark',
  },
  sunset: {
    id: 'sunset',
    label: 'Pôr do Sol',
    emoji: '🌅',
    desc: 'Dourado e caloroso',
    home: ['#FFF4EC', '#FFE0CC', '#FFB88C', '#FF8C69'],
    counter: ['#FF6B6B', '#FF8C42', '#FFB347'],
    accent: '#E8623A',
    accentLight: '#FF8C42',
    accentDark: '#B8431F',
    textDark: '#3D1A0F',
    textMedium: '#8B5240',
    textLight: '#C4977E',
    cardBg: '#FFFFFF',
    chipBg: '#FFF1E8',
    statusBar: 'dark',
  },
  lavender: {
    id: 'lavender',
    label: 'Lavanda',
    emoji: '💜',
    desc: 'Roxo sonhador',
    home: ['#F6F0FF', '#E6D6FF', '#CBB0F5', '#A98AE6'],
    counter: ['#7B52AB', '#9B6FCC', '#C4A0F0'],
    accent: '#7B52AB',
    accentLight: '#9B6FCC',
    accentDark: '#553476',
    textDark: '#2A1542',
    textMedium: '#6B4E8B',
    textLight: '#A38FC0',
    cardBg: '#FFFFFF',
    chipBg: '#F3ECFF',
    statusBar: 'dark',
  },
  ocean: {
    id: 'ocean',
    label: 'Oceano',
    emoji: '🌊',
    desc: 'Azul calmo e profundo',
    home: ['#EEF7FF', '#CFE8FF', '#9FCFF5', '#6FB3E8'],
    counter: ['#2E7DB8', '#4A9FD4', '#7FC4ED'],
    accent: '#2E7DB8',
    accentLight: '#4A9FD4',
    accentDark: '#1C5582',
    textDark: '#0F2A3D',
    textMedium: '#40647B',
    textLight: '#8AA8BC',
    cardBg: '#FFFFFF',
    chipBg: '#EAF4FD',
    statusBar: 'dark',
  },
  midnight: {
    id: 'midnight',
    label: 'Meia-noite',
    emoji: '🌙',
    desc: 'Escuro e apaixonante',
    home: ['#1A0A20', '#2C1654', '#5C1A35', '#8B2252'],
    counter: ['#7B1540', '#C0395A', '#E8527A'],
    accent: '#E8527A',
    accentLight: '#FF85A1',
    accentDark: '#8B1E3F',
    textDark: '#FFFFFF',
    textMedium: '#E8B8CC',
    textLight: '#B98AA0',
    cardBg: 'rgba(255,255,255,0.10)',
    chipBg: 'rgba(255,255,255,0.12)',
    statusBar: 'light',
  },
};

export const THEME_LIST = Object.values(THEMES);

export const DEFAULT_THEME = 'rose';
